// AUTO-GENERATED by _migrate_build.js — seeds the hub's localStorage ONCE
// with progress migrated from the old tracker snapshot (matched by title).
// Guarded by a version flag so it never clobbers later edits.
(function(){
  var FLAG='lt-hub-seed-version', VER="migrate-2026-07-23";
  var DATA_KEY='lt-hub-data-v1', STATE_KEY='lt-hub-state-v1';
  try{
    if(localStorage.getItem(FLAG)===VER) return;
    // Merge (don't clobber) if the user already has local data.
    var curD={}; try{curD=JSON.parse(localStorage.getItem(DATA_KEY))||{};}catch(e){}
    var curS={}; try{curS=JSON.parse(localStorage.getItem(STATE_KEY))||{};}catch(e){}
    var mig={"custom":{},"edits":{},"topicEdits":{},"sectionEdits":{},"order":{},"settings":{"weeklyGoal":12}};
    var migState={"b:🎓 Analytics Vidhya - Agentic AI Pioneer Program::Program::0":"done","b:🎓 Systematically Improving RAG Applications::Weekly Schedule::0":"prog","b:📊 RAG, Evals & Production::RAG::2":"prog","b:🧠 Agentic Memory & Context::Hands-on Builds::3":"prog","b:AI Engineering Projects::Krish Naik Academy::11":"prog","b:📖 Books & Reading List::Other Books::2":"prog","b:📰 Newsletters & Substacks and Medium Blogs::Medium Blogs::1":"prog","b:📰 Newsletters & Substacks and Medium Blogs::Medium Blogs::2":"prog","b:📰 Newsletters & Substacks and Medium Blogs::Medium Blogs::3":"prog","b:📰 Newsletters & Substacks and Medium Blogs::Medium Blogs::4":"prog","b:📰 Newsletters & Substacks and Medium Blogs::Medium Blogs::14":"prog"};
    // shallow-merge custom modules/topics
    curD.custom=curD.custom||{};
    Object.keys(mig.custom).forEach(function(m){curD.custom[m]=curD.custom[m]||{};Object.keys(mig.custom[m]).forEach(function(t){if(!curD.custom[m][t])curD.custom[m][t]=mig.custom[m][t];});});
    ['edits','topicEdits','sectionEdits','order','settings'].forEach(function(k){curD[k]=curD[k]||mig[k];});
    Object.keys(migState).forEach(function(id){if(!(id in curS))curS[id]=migState[id];});
    localStorage.setItem(DATA_KEY,JSON.stringify(curD));
    localStorage.setItem(STATE_KEY,JSON.stringify(curS));
    localStorage.setItem(FLAG,VER);
  }catch(e){}
})();
